### ISSUE TITLE
安装 redis-memory-server 时发生错误.

### ISSUE THREAD

**Issue by JV-X** [didi/xiaoju-survey#454]
我在通过 docker 构建 xiaoju-survey 环境，当我装好docker并尝试```docker build -t xiaoju-survey-app .```命令的时候，出现报错：

```
root@hygx:/home/hygx/code/xiaoju-survey# docker build -t xiaoju-survey-app .
[+] Building 283.5s (12/12) FINISHED                                                                     docker:default
 => [internal] load build definition from Dockerfile                                                               0.0s
 => => transferring dockerfile: 664B                                                                               0.0s
 => [internal] load metadata for docker.io/library/node:18-slim                                                    1.6s
 => [internal] load .dockerignore                                                                                  0.0s
 => => transferring context: 2B                                                                                    0.0s
 => [1/8] FROM docker.io/library/node:18-slim@sha256:f070ad60a68c26f3d3553385dddd48622012f90de1837daa480edfc7aa92  0.0s
 => [internal] load build context                                                                                  0.2s
 => => transferring context: 1.08MB                                                                                0.2s
 => CACHED [2/8] WORKDIR /xiaoju-survey                                                                            0.0s
 => CACHED [3/8] COPY . /xiaoju-survey                                                                             0.0s
 => CACHED [4/8] RUN apt-get update && apt-get install -y nginx                                                    0.0s
 => CACHED [5/8] RUN npm config set registry https://registry.npmjs.org/                                           0.0s
 => CACHED [6/8] RUN cd /xiaoju-survey/web && npm install && npm run build-only                                    0.0s
 => CACHED [7/8] COPY ./nginx/nginx.conf /etc/nginx/nginx.conf                                                     0.0s
 => ERROR [8/8] RUN cd /xiaoju-survey/server && npm install && npm run build                                     281.7s
------
 > [8/8] RUN cd /xiaoju-survey/server && npm install && npm run build:
249.8 npm warn deprecated eslint@8.57.1: This version is no longer supported. Please see https://eslint.org/version-support for other options.
281.6 npm error code 1
281.6 npm error path /xiaoju-survey/server/node_modules/redis-memory-server
281.6 npm error command failed
281.6 npm error command sh -c node ./scripts/postinstall
281.6 npm error /xiaoju-survey/server/node_modules/lockfile/lockfile.js:34
281.6 npm error onExit(function () {
281.6 npm error ^
281.6 npm error
281.6 npm error TypeError: onExit is not a function
281.6 npm error     at Object.<anonymous> (/xiaoju-survey/server/node_modules/lockfile/lockfile.js:34:1)
281.6 npm error     at Module._compile (node:internal/modules/cjs/loader:1364:14)
281.6 npm error     at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
281.6 npm error     at Module.load (node:internal/modules/cjs/loader:1203:32)
281.6 npm error     at Module._load (node:internal/modules/cjs/loader:1019:12)
281.6 npm error     at Module.require (node:internal/modules/cjs/loader:1231:19)
281.6 npm error     at require (node:internal/modules/helpers:177:18)
281.6 npm error     at Object.<anonymous> (/xiaoju-survey/server/node_modules/redis-memory-server/lib/util/RedisBinary.js:20:36)
281.6 npm error     at Module._compile (node:internal/modules/cjs/loader:1364:14)
281.6 npm error     at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
281.6 npm error
281.6 npm error Node.js v18.20.5
281.6 npm error A complete log of this run can be found in: /root/.npm/_logs/2024-11-29T09_05_46_134Z-debug-0.log
------
Dockerfile:21
--------------------
  19 |     COPY ./nginx/nginx.conf /etc/nginx/nginx.conf
  20 |
  21 | >>> RUN cd /xiaoju-survey/server && npm install && npm run build
  22 |
  23 |     # 暴露端口 需要跟nginx的port一致
--------------------
ERROR: failed to solve: process "/bin/sh -c cd /xiaoju-survey/server && npm install && npm run build" did not complete successfully: exit code: 1
```
我不太懂前端，对这个问题感到无助，有什么建议吗？

感谢您的回复.

**Comment by sudoooooo** [comment]
@JV-X 您好，可以先把sever/package.json里的redis-memory-server先删了，暂时用不到。

后续新功能里会用到这个包，请问您是什么系统吗？我们后续开发的时候兼容下。

**Comment by JV-X** [comment]
> @JV-X 您好，可以先把sever/package.json里的redis-memory-server先删了，暂时用不到。
> 
> 后续新功能里会用到这个包，请问您是什么系统吗？我们后续开发的时候兼容下。

是 windows11 下的WSL2，用docker安装的

**Comment by sudoooooo** [comment]
问题已经解决：https://github.com/didi/xiaoju-survey/issues/456
