### ISSUE TITLE
构建docker镜像时出现nest: Permission denied

### ISSUE THREAD

**Issue by JV-X** [didi/xiaoju-survey#456]
你好，我在尝试构建xiaoju-survey的docker镜像，当我根据 https://github.com/didi/xiaoju-survey/issues/454 的建议删除掉redis依赖后，产生过构建，得到了以下报错，我尝试了在执行```docker build -t xiaoju-survey-app .```的时候加上sudo，得到了同样的结果

error log：

```
(base) hygx@hygx:~/code/xiaoju-survey$ sudo docker build -t xiaoju-survey-app .
[sudo] password for hygx:
[+] Building 37.2s (12/12) FINISHED                                                                      docker:default
 => [internal] load build definition from Dockerfile                                                               0.0s
 => => transferring dockerfile: 664B                                                                               0.0s
 => [internal] load metadata for docker.io/library/node:18-slim                                                    2.9s
 => [internal] load .dockerignore                                                                                  0.0s
 => => transferring context: 2B                                                                                    0.0s
 => [1/8] FROM docker.io/library/node:18-slim@sha256:f070ad60a68c26f3d3553385dddd48622012f90de1837daa480edfc7aa92  0.0s
 => [internal] load build context                                                                                  0.8s
 => => transferring context: 1.08MB                                                                                0.7s
 => CACHED [2/8] WORKDIR /xiaoju-survey                                                                            0.0s
 => CACHED [3/8] COPY . /xiaoju-survey                                                                             0.0s
 => CACHED [4/8] RUN apt-get update && apt-get install -y nginx                                                    0.0s
 => CACHED [5/8] RUN npm config set registry https://registry.npmjs.org/                                           0.0s
 => CACHED [6/8] RUN cd /xiaoju-survey/web && npm install && npm run build-only                                    0.0s
 => CACHED [7/8] COPY ./nginx/nginx.conf /etc/nginx/nginx.conf                                                     0.0s
 => ERROR [8/8] RUN cd /xiaoju-survey/server && npm install && npm run build                                      33.4s
------
 > [8/8] RUN cd /xiaoju-survey/server && npm install && npm run build:
27.64 npm warn deprecated eslint@8.57.1: This version is no longer supported. Please see https://eslint.org/version-support for other options.
33.08
33.08 added 8 packages, removed 83 packages, changed 140 packages, and audited 863 packages in 33s
33.08
33.08 131 packages are looking for funding
33.08   run `npm fund` for details
33.08
33.08 2 high severity vulnerabilities
33.08
33.08 To address all issues (including breaking changes), run:
33.08   npm audit fix --force
33.08
33.08 Run `npm audit` for details.
33.16
33.16 > xiaoju-survey-server@1.3.0 build
33.16 > nest build
33.16
33.16 sh: 1: nest: Permission denied
------
Dockerfile:21
--------------------
  19 |     COPY ./nginx/nginx.conf /etc/nginx/nginx.conf
  20 |
  21 | >>> RUN cd /xiaoju-survey/server && npm install && npm run build
  22 |
  23 |     # 暴露端口 需要跟nginx的port一致
--------------------
ERROR: failed to solve: process "/bin/sh -c cd /xiaoju-survey/server && npm install && npm run build" did not complete successfully: exit code: 127
```

**Comment by luch1994** [comment]
1、先尝试不使用docker，能否正常install和build，手动进入server目录，执行 npm install 和 npm run build 
2、可以尝试把package.json中的build命令，"build": "nest build", 改成 "build": "npx nest build", 加上npx会默认使用本地安装的 @nestjs/cli

**Comment by JV-X** [comment]
我尝试 `npm install`，看起来是成功了，但是执行npm run build 的时候显示permission denied，加了sudo也还是不行
```
(base) hygx@hygx:~/code/xiaoju-survey/server$ npm install
(node:69727) ExperimentalWarning: CommonJS module /usr/lib/node_modules/npm/node_modules/debug/src/node.js is loading ES Module /usr/lib/node_modules/npm/node_modules/supports-color/index.js using require().
Support for loading ES Module in require() is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
npm warn deprecated eslint@8.57.1: This version is no longer supported. Please see https://eslint.org/version-support for other options.

added 8 packages, removed 83 packages, and changed 140 packages in 48s

131 packages are looking for funding
  run `npm fund` for details
(base) hygx@hygx:~/code/xiaoju-survey/server$ npm run build

> xiaoju-survey-server@1.3.0 build
> npx nest build

(node:54706) ExperimentalWarning: CommonJS module /usr/lib/node_modules/npm/node_modules/debug/src/node.js is loading ES Module /usr/lib/node_modules/npm/node_modules/supports-color/index.js using require().
Support for loading ES Module in require() is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
sh: 1: nest: Permission denied
(base) hygx@hygx:~/code/xiaoju-survey/server$ sudo npm run build
[sudo] password for hygx:

> xiaoju-survey-server@1.3.0 build
> npx nest build

(node:55258) ExperimentalWarning: CommonJS module /usr/lib/node_modules/npm/node_modules/debug/src/node.js is loading ES Module /usr/lib/node_modules/npm/node_modules/supports-color/index.js using require().
Support for loading ES Module in require() is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
sh: 1: nest: Permission denied
```

**Comment by luch1994** [comment]
方便再提供一个你的node环境吗？我们尽量先尝试复现一下你的问题

还可以尝试一下这两个方案：
1、全局安全@nest/cli，执行 npm install -g @nest/cli ，然后把 package.json中的build命令改回 "build": "nest build" ，重新执行一下build命令看是否还会报错
2、修改nest命令的权限：chmod u+x server/node_modules/@nestjs/cli/bin/nest.js 再重新执行一下 npm run build或者npx nest build

**Comment by JV-X** [comment]
我的node环境：
```
(auralis_env) hygx@hygx:~/code/xiaoju-survey/server$ node -v
v23.2.0
```
执行` npm install -g @nest/cli` 结果是这样:
```
(auralis_env) hygx@hygx:~/code/xiaoju-survey/server$ npm install -g @nest/cli
(node:119167) ExperimentalWarning: CommonJS module /usr/lib/node_modules/npm/node_modules/debug/src/node.js is loading ES Module /usr/lib/node_modules/npm/node_modules/supports-color/index.js using require().
Support for loading ES Module in require() is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
npm error code E404
npm error 404 Not Found - GET https://registry.npmjs.org/@nest%2fcli - Not found
npm error 404
npm error 404  '@nest/cli@*' is not in this registry.
npm error 404
npm error 404 Note that you can also install from a
npm error 404 tarball, folder, http url, or git url.
npm error A complete log of this run can be found in: /home/hygx/.npm/_logs/2024-12-03T09_14_18_187Z-debug-0.log
```
修改nest.js命令权限后执行npm run build的结果是这样：
```
(auralis_env) hygx@hygx:~/code/xiaoju-survey/server$ chmod u+x node_modules/@nestjs/cli/bin/nest.js
(auralis_env) hygx@hygx:~/code/xiaoju-survey/server$ ll node_modules/@nestjs/cli/bin/
total 16
drwxrwxr-x  2 hygx hygx 4096 Dec  2 17:46 ./
drwxrwxr-x 11 hygx hygx 4096 Dec  2 17:46 ../
-rw-rw-r--  1 hygx hygx   31 Dec  2 17:46 nest.d.ts
-rwxrw-r--  1 hygx hygx  923 Dec  2 17:46 nest.js*
(auralis_env) hygx@hygx:~/code/xiaoju-survey/server$ npm run build

> xiaoju-survey-server@1.3.0 build
> npx nest build

(node:119692) ExperimentalWarning: CommonJS module /usr/lib/node_modules/npm/node_modules/debug/src/node.js is loading ES Module /usr/lib/node_modules/npm/node_modules/supports-color/index.js using require().
Support for loading ES Module in require() is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
/home/hygx/code/xiaoju-survey/server/node_modules/path-scurry/dist/commonjs/index.js:124
class ResolveCache extends lru_cache_1.LRUCache {
                                       ^

TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (/home/hygx/code/xiaoju-survey/server/node_modules/path-scurry/dist/commonjs/index.js:124:40)
    at Module._compile (node:internal/modules/cjs/loader:1550:14)
    at Object..js (node:internal/modules/cjs/loader:1702:10)
    at Module.load (node:internal/modules/cjs/loader:1307:32)
    at Function._load (node:internal/modules/cjs/loader:1121:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:219:24)
    at Module.require (node:internal/modules/cjs/loader:1329:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (/home/hygx/code/xiaoju-survey/server/node_modules/glob/dist/commonjs/glob.js:6:23)

Node.js v23.2.0
(auralis_env) hygx@hygx:~/code/xiaoju-survey/server$
```

**Comment by luch1994** [comment]
不好意思，今天给你发的包名打错了，全局安装nestjs的cli工具应该是执行 npm install -g @nestjs/cli，不过你提供的问题跟这个全局包没关系，可以不用安装

你修改权限后，有个新的报错，建议node换成18的版本，22、20和18都是LTS版本相对比较稳定，切换node版本后，需要删掉node_modules文件夹，重新执行 npm install，再修改一下权限，再执行npm run build

**Comment by JV-X** [comment]
感谢您的回复，我降级之后npm install 会报错：
```
(auralis_env) hygx@hygx:~/code/xiaoju-survey/server$ node -v
v18.20.5
(auralis_env) hygx@hygx:~/code/xiaoju-survey/server$ npm -v
10.8.2
(auralis_env) hygx@hygx:~/code/xiaoju-survey/server$ npm install
npm error Invalid Version:
npm error A complete log of this run can be found in: /home/hygx/.npm/_logs/2024-12-04T02_05_57_609Z-debug-0.log
```

完整日志：
[2024-12-04T02_05_57_609Z-debug-0.log](https://github.com/user-attachments/files/18001668/2024-12-04T02_05_57_609Z-debug-0.log)

**Comment by luch1994** [comment]
看日志好像是某个包的版本没匹配上，可以删除node_modules后，再把当前目录的package-lock.json删除试一下，删除node_modules和lock文件之后，还不行的话，可以再试试清除npm的缓存 npm cache clean --force

**Comment by JV-X** [comment]
好了，本地构建成功了，感谢您的回答！阿里嘎托！

**Comment by JV-X** [comment]
> 看日志好像是某个包的版本没匹配上，可以删除node_modules后，再把当前目录的package-lock.json删除试一下，删除node_modules和lock文件之后，还不行的话，可以再试试清除npm的缓存 npm cache clean --force


好了，本地构建成功了，感谢您的回答！阿里嘎托！

**Comment by sudoooooo** [comment]
> > 看日志好像是某个包的版本没匹配上，可以删除node_modules后，再把当前目录的package-lock.json删除试一下，删除node_modules和lock文件之后，还不行的话，可以再试试清除npm的缓存 npm cache clean --force
> 
> 好了，本地构建成功了，感谢您的回答！阿里嘎托！

@JV-X  先关闭issue了，欢迎随时交流 🤝。
