### ISSUE TITLE
⚠️ 重大CHANGELOG

### ISSUE THREAD

**Issue by sudoooooo** [didi/xiaoju-survey#48]
# 2023.1.17
### 变更
优化服务端环境变量引入方式，主要优化了导入方式和命名规范
### 来源**
@alwayrun PR 🎉
### 影响：
⚠️ 服务重新部署前，特别注意您的环境配置：
1、xiaojuSurveyMongoUrl 规范化成 XIAOJU_SURVEY_MONGO_URL
2、xiaojuSurveyJwtSecret  规范化成 XIAOJU_SURVEY_JWT_SECRET
需重新配置环境变量
![image](https://github.com/didi/xiaoju-survey/assets/16012672/eb1a819e-c779-43a9-8d2a-230c0407f445)
![image](https://github.com/didi/xiaoju-survey/assets/16012672/674aaee1-5235-470c-9846-0b8e14147112)
![image](https://github.com/didi/xiaoju-survey/assets/16012672/41b1b858-ac2d-4947-b6ca-727acafacb3f)

**Comment by coder-xiaomo** [comment]
@sudoooooo 是否考虑将配置从环境变量转移到配置文件呢，这样配置起来会方便一些，也方便后续扩展

**Comment by sudoooooo** [comment]
@coder-xiaomo 你好，server架构升级后统一在配置文件维护，升级后的可在feature/server试用，本周会合并到develop和main分支。

**Comment by linux-y** [comment]
崩溃啦，为什么我用docker启动一直报连不上数据库？
[root@redis survey]# docker -v
Docker version 19.03.5, build 633a0ea
[root@redis survey]# docker-compose -v
docker-compose version 1.24.1, build 4667896b
[root@redis survey]# cat /etc/redhat-release 
CentOS Linux release 8.3.2011
[root@redis survey]# uname -a
Linux redis 4.18.0-240.el8.x86_64 #1 SMP Fri Sep 25 19:48:47 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

docker-compose.yml如下：
`[root@redis survey]# docker logs -f xiaoju-survey

> server@0.0.1 start:prod
> NODE_ENV=production node dist/main

[Nest] 19  - 03/25/2024, 10:03:02 AM     LOG [NestFactory] Starting Nest application...
[Nest] 19  - 03/25/2024, 10:03:02 AM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +34ms
[Nest] 19  - 03/25/2024, 10:03:02 AM     LOG [InstanceLoader] ConfigHostModule dependencies initialized +1ms
[Nest] 19  - 03/25/2024, 10:03:02 AM     LOG [InstanceLoader] ServeStaticModule dependencies initialized +0ms
[Nest] 19  - 03/25/2024, 10:03:02 AM     LOG [InstanceLoader] ConfigModule dependencies initialized +0ms
[Nest] 19  - 03/25/2024, 10:03:02 AM     LOG [InstanceLoader] ConfigModule dependencies initialized +0ms
[Nest] 19  - 03/25/2024, 10:03:02 AM     LOG [InstanceLoader] AppModule dependencies initialized +25ms
[Nest] 19  - 03/25/2024, 10:03:02 AM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (1)...
MongoServerError: Invalid database name: ''
    at Connection.onMessage (/xiaoju-survey/server/node_modules/mongodb/lib/cmap/connection.js:202:26)
    at MessageStream.<anonymous> (/xiaoju-survey/server/node_modules/mongodb/lib/cmap/connection.js:61:60)
    at MessageStream.emit (node:events:513:28)
    at processIncomingData (/xiaoju-survey/server/node_modules/mongodb/lib/cmap/message_stream.js:124:16)
    at MessageStream._write (/xiaoju-survey/server/node_modules/mongodb/lib/cmap/message_stream.js:33:9)
    at writeOrBuffer (node:internal/streams/writable:391:12)
    at _write (node:internal/streams/writable:332:10)
    at MessageStream.Writable.write (node:internal/streams/writable:336:10)
    at Socket.ondata (node:internal/streams/readable:754:22)
    at Socket.emit (node:events:513:28)
[Nest] 19  - 03/25/2024, 10:03:05 AM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (2)...
MongoServerError: Invalid database name: ''
    at Connection.onMessage (/xiaoju-survey/server/node_modules/mongodb/lib/cmap/connection.js:202:26)
    at MessageStream.<anonymous> (/xiaoju-survey/server/node_modules/mongodb/lib/cmap/connection.js:61:60)
    at MessageStream.emit (node:events:513:28)
    at processIncomingData (/xiaoju-survey/server/node_modules/mongodb/lib/cmap/message_stream.js:124:16)
    at MessageStream._write (/xiaoju-survey/server/node_modules/mongodb/lib/cmap/message_stream.js:33:9)
    at writeOrBuffer (node:internal/streams/writable:391:12)
    at _write (node:internal/streams/writable:332:10)
    at MessageStream.Writable.write (node:internal/streams/writable:336:10)
    at Socket.ondata (node:internal/streams/readable:754:22)
    at Socket.emit (node:events:513:28)
^C
[root@redis survey]# cat docker-compose.yml .env 
version: "3.6"
services:
  mongo:
    image: mongo:4
    container_name: xiaoju-survey-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: syy# 默认使用系统的环境变量
      MONGO_INITDB_ROOT_PASSWORD: syy123 # 默认使用系统的环境变量
    ports:
      - "27017:27017" # 数据库端口
    volumes:
      - mongo-volume:/data/db # xiaoju-survey-data/db/data:/data/db
    networks:
      - xiaoju-survey

  xiaoju-survey:
    image: "xiaojusurvey/xiaoju-survey:1.0.4"
    container_name: xiaoju-survey
    restart: always
    ports:
      - "8080:3000" # API端口
    environment:
      MONGO_INITDB_ROOT_USERNAME: syy # 默认使用系统的环境变量
      MONGO_INITDB_ROOT_PASSWORD: syy123 # 默认使用系统的环境变量
      XIAOJU_SURVEY_MONGO_DB_NAME: xiaojuSurvey
      XIAOJU_SURVEY_MONGO_AUTH_SOURCE: 
      XIAOJU_SURVEY_MONGO_URL: mongodb://syy:syy123@192.168.2.246:27017/xiaojuSurvey
      #XIAOJU_SURVEY_MONGO_URL: mongodb://syy:syy123@xiaoju-survey-mongo:27017 # docker-compose 会根据容器名称自动处理
    links:
      - mongo:mongo
    depends_on:
      - mongo
    networks:
      - xiaoju-survey

volumes:
  mongo-volume:

networks:
  xiaoju-survey:
    name: xiaoju-survey
    driver: bridge
MONGO_INITDB_ROOT_USERNAME=syy
MONGO_INITDB_ROOT_PASSWORD=syy123
XIAOJU_SURVEY_MONGO_DB_NAME=xiaojuSurvey
XIAOJU_SURVEY_MONGO_URL=mongodb://localhost:27017
XIAOJU_SURVEY_MONGO_AUTH_SOURCE=

XIAOJU_SURVEY_RESPONSE_AES_ENCRYPT_SECRET_KEY=dataAesEncryptSecretKey
XIAOJU_SURVEY_HTTP_DATA_ENCRYPT_TYPE=rsa

XIAOJU_SURVEY_JWT_SECRET=xiaojuSurveyJwtSecret
XIAOJU_SURVEY_JWT_EXPIRES_IN=8h

XIAOJU_SURVEY_LOGGER_FILENAME=./logs/app.log
`

**Comment by sudoooooo** [comment]
> 崩溃啦，为什么我用docker启动一直报连不上数据库？ [root@redis survey]# docker -v Docker version 19.03.5, build 633a0ea [root@redis survey]# docker-compose -v docker-compose version 1.24.1, build 4667896b [root@redis survey]# cat /etc/redhat-release CentOS Linux release 8.3.2011 [root@redis survey]# uname -a Linux redis 4.18.0-240.el8.x86_64 #1 SMP Fri Sep 25 19:48:47 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
> 
> docker-compose.yml如下： `[root@redis survey]# docker logs -f xiaoju-survey
> 
> > server@0.0.1 start:prod
> > NODE_ENV=production node dist/main
> 
> [Nest] 19 - 03/25/2024, 10:03:02 AM LOG [NestFactory] Starting Nest application... [Nest] 19 - 03/25/2024, 10:03:02 AM LOG [InstanceLoader] TypeOrmModule dependencies initialized +34ms [Nest] 19 - 03/25/2024, 10:03:02 AM LOG [InstanceLoader] ConfigHostModule dependencies initialized +1ms [Nest] 19 - 03/25/2024, 10:03:02 AM LOG [InstanceLoader] ServeStaticModule dependencies initialized +0ms [Nest] 19 - 03/25/2024, 10:03:02 AM LOG [InstanceLoader] ConfigModule dependencies initialized +0ms [Nest] 19 - 03/25/2024, 10:03:02 AM LOG [InstanceLoader] ConfigModule dependencies initialized +0ms [Nest] 19 - 03/25/2024, 10:03:02 AM LOG [InstanceLoader] AppModule dependencies initialized +25ms [Nest] 19 - 03/25/2024, 10:03:02 AM ERROR [TypeOrmModule] Unable to connect to the database. Retrying (1)... MongoServerError: Invalid database name: '' at Connection.onMessage (/xiaoju-survey/server/node_modules/mongodb/lib/cmap/connection.js:202:26) at MessageStream. (/xiaoju-survey/server/node_modules/mongodb/lib/cmap/connection.js:61:60) at MessageStream.emit (node:events:513:28) at processIncomingData (/xiaoju-survey/server/node_modules/mongodb/lib/cmap/message_stream.js:124:16) at MessageStream._write (/xiaoju-survey/server/node_modules/mongodb/lib/cmap/message_stream.js:33:9) at writeOrBuffer (node:internal/streams/writable:391:12) at _write (node:internal/streams/writable:332:10) at MessageStream.Writable.write (node:internal/streams/writable:336:10) at Socket.ondata (node:internal/streams/readable:754:22) at Socket.emit (node:events:513:28) [Nest] 19 - 03/25/2024, 10:03:05 AM ERROR [TypeOrmModule] Unable to connect to the database. Retrying (2)... MongoServerError: Invalid database name: '' at Connection.onMessage (/xiaoju-survey/server/node_modules/mongodb/lib/cmap/connection.js:202:26) at MessageStream. (/xiaoju-survey/server/node_modules/mongodb/lib/cmap/connection.js:61:60) at MessageStream.emit (node:events:513:28) at processIncomingData (/xiaoju-survey/server/node_modules/mongodb/lib/cmap/message_stream.js:124:16) at MessageStream._write (/xiaoju-survey/server/node_modules/mongodb/lib/cmap/message_stream.js:33:9) at writeOrBuffer (node:internal/streams/writable:391:12) at _write (node:internal/streams/writable:332:10) at MessageStream.Writable.write (node:internal/streams/writable:336:10) at Socket.ondata (node:internal/streams/readable:754:22) at Socket.emit (node:events:513:28) ^C [root@redis survey]# cat docker-compose.yml .env version: "3.6" services: mongo: image: mongo:4 container_name: xiaoju-survey-mongo restart: always environment: MONGO_INITDB_ROOT_USERNAME: syy# 默认使用系统的环境变量 MONGO_INITDB_ROOT_PASSWORD: syy123 # 默认使用系统的环境变量 ports: - "27017:27017" # 数据库端口 volumes: - mongo-volume:/data/db # xiaoju-survey-data/db/data:/data/db networks: - xiaoju-survey
> 
> xiaoju-survey: image: "xiaojusurvey/xiaoju-survey:1.0.4" container_name: xiaoju-survey restart: always ports: - "8080:3000" # API端口 environment: MONGO_INITDB_ROOT_USERNAME: syy # 默认使用系统的环境变量 MONGO_INITDB_ROOT_PASSWORD: syy123 # 默认使用系统的环境变量 XIAOJU_SURVEY_MONGO_DB_NAME: xiaojuSurvey XIAOJU_SURVEY_MONGO_AUTH_SOURCE: XIAOJU_SURVEY_MONGO_URL: mongodb://syy:syy123@192.168.2.246:27017/xiaojuSurvey #XIAOJU_SURVEY_MONGO_URL: mongodb://syy:syy123@xiaoju-survey-mongo:27017 # docker-compose 会根据容器名称自动处理 links: - mongo:mongo depends_on: - mongo networks: - xiaoju-survey
> 
> volumes: mongo-volume:
> 
> networks: xiaoju-survey: name: xiaoju-survey driver: bridge MONGO_INITDB_ROOT_USERNAME=syy MONGO_INITDB_ROOT_PASSWORD=syy123 XIAOJU_SURVEY_MONGO_DB_NAME=xiaojuSurvey XIAOJU_SURVEY_MONGO_URL=mongodb://localhost:27017 XIAOJU_SURVEY_MONGO_AUTH_SOURCE=
> 
> XIAOJU_SURVEY_RESPONSE_AES_ENCRYPT_SECRET_KEY=dataAesEncryptSecretKey XIAOJU_SURVEY_HTTP_DATA_ENCRYPT_TYPE=rsa
> 
> XIAOJU_SURVEY_JWT_SECRET=xiaojuSurveyJwtSecret XIAOJU_SURVEY_JWT_EXPIRES_IN=8h
> 
> XIAOJU_SURVEY_LOGGER_FILENAME=./logs/app.log `

目测是这个问题：https://github.com/didi/xiaoju-survey/issues/70
